typography_spectrum: 0.6283263263758272
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.4932713301386684
  lightness: 0.846719924127683
  saturation: 0.32069906406104565
  rhythmicContrast: 0.34522880311124027
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.15671342355199158
analytics:
  google: null
  facebook: null
  twitter: null
name: Pet Plants
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
